/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SucessoRouteImport } from './routes/sucesso'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as CapturaRouteImport } from './routes/captura'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'

const SucessoRoute = SucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturaRoute = CapturaRouteImport.update({
  id: '/captura',
  path: '/captura',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/captura': typeof CapturaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/sucesso': typeof SucessoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/captura': typeof CapturaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/sucesso': typeof SucessoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/captura': typeof CapturaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/sucesso': typeof SucessoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cadastro' | '/captura' | '/minha-conta' | '/sucesso'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cadastro' | '/captura' | '/minha-conta' | '/sucesso'
  id: '__root__' | '/' | '/cadastro' | '/captura' | '/minha-conta' | '/sucesso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CapturaRoute: typeof CapturaRoute
  MinhaContaRoute: typeof MinhaContaRoute
  SucessoRoute: typeof SucessoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sucesso': {
      id: '/sucesso'
      path: '/sucesso'
      fullPath: '/sucesso'
      preLoaderRoute: typeof SucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captura': {
      id: '/captura'
      path: '/captura'
      fullPath: '/captura'
      preLoaderRoute: typeof CapturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CapturaRoute: CapturaRoute,
  MinhaContaRoute: MinhaContaRoute,
  SucessoRoute: SucessoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
